### ISSUE TITLE
Kerl support

### ISSUE THREAD

**Issue by mmzeeman** [NigelRook/vscode-linter-erlc#4]
Kerl makes it possible to switch between erlang versions. 

See: https://github.com/kerl/kerl

When one uses kerl there is no direct erlc executable path. You first have to activate a build before you can use it. 

Is it possible to support this?

**Comment by NigelRook** [comment]
Kerl does provide a direct path to its various erlang versions, you can use `kerl path` to find the path of your current active installation, append `bin/erlc` to that path to get the full path.

You can also provide just `erlc` as the extension path and it should be resolved as any other executable would. Note that kerl works by editing your `PATH` environment variable though, which means you'll have to run kerl before starting vscode, and in a parent shell.
